-- Esquema Tesix adaptado de MySQL a PostgreSQL (Supabase)

CREATE TABLE IF NOT EXISTS usuarios (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    creado_en TIMESTAMP NULL DEFAULT NULL,
    tema VARCHAR(20) NULL DEFAULT 'oscuro'
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_usuarios_username ON usuarios (username);

CREATE TABLE IF NOT EXISTS escaneos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    target VARCHAR(255) NOT NULL,
    titulo VARCHAR(150) NULL DEFAULT NULL,
    subtitulo VARCHAR(255) NULL DEFAULT NULL,
    total_dispositivos INT NULL DEFAULT NULL,
    fecha TIMESTAMP NULL DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS ix_escaneos_fecha ON escaneos (fecha);
CREATE INDEX IF NOT EXISTS ix_escaneos_usuario_id ON escaneos (usuario_id);

CREATE TABLE IF NOT EXISTS resultados_escaneo (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    escaneo_id INT NOT NULL,
    item VARCHAR(255) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    explicacion TEXT NULL DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS ix_resultados_escaneo_escaneo_id ON resultados_escaneo (escaneo_id);

CREATE TABLE IF NOT EXISTS vulnerabilidades (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    escaneo_id INT NOT NULL,
    id_malware VARCHAR(100) NULL DEFAULT NULL,
    cve VARCHAR(100) NULL DEFAULT NULL,
    nombre VARCHAR(250) NULL DEFAULT NULL,
    descripcion TEXT NULL DEFAULT NULL,
    tipo VARCHAR(50) NULL DEFAULT NULL,
    severity VARCHAR(20) NULL DEFAULT NULL,
    risk VARCHAR(20) NULL DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS fk_vul_escaneo ON vulnerabilidades (escaneo_id);

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'escaneos_ibfk_1'
    ) THEN
        ALTER TABLE escaneos ADD CONSTRAINT escaneos_ibfk_1
            FOREIGN KEY (usuario_id) REFERENCES usuarios (id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'resultados_escaneo_ibfk_1'
    ) THEN
        ALTER TABLE resultados_escaneo ADD CONSTRAINT resultados_escaneo_ibfk_1
            FOREIGN KEY (escaneo_id) REFERENCES escaneos (id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_vul_escaneo'
    ) THEN
        ALTER TABLE vulnerabilidades ADD CONSTRAINT fk_vul_escaneo
            FOREIGN KEY (escaneo_id) REFERENCES escaneos (id) ON DELETE CASCADE;
    END IF;
END $$;
